### PR TITLE
Add "v2" subprotocol (for SSH)

### PR DESCRIPTION
**Pull request by cdzombak**
This will replace the “banner” subprotocol for use with the ZGrab XSSH grabber.

### CODE REVIEW

**Comment by zakird** [comment]
In this situation I think that SSHv2 would be a protocol not a subprotocol. I'm not sure if this is the right name.

**Comment by dadrian** [comment]
I don't have strong opinions, just name it something.

**Comment by dadrian** [comment]
Although I will note if we leave name as it, then we end up with `p22.ssh.ssh_v2` which is kind of awkward.

**Comment by zakird** [comment]
What kind of handshake is this? What kind of key exchange are we prioritizting?

**Comment by cdzombak** [comment]
> I don't have strong opinions, just name it something.
…
> I'm not sure if this is the right name. That said I don't know what is.
…
> Although I will note if we leave name as it, then we end up with `p22.ssh.ssh_v2` which is kind of awkward.

Agreed on all counts.

> What kind of handshake is this? What kind of key exchange are we prioritizting?

Whatever x/ssh does by default?

**Comment by dadrian** [comment]
We should probably do something like send whatever the most recent OpenSSH sends and then just call that `p22.ssh.v2`.

**Comment by dadrian** [comment]
(similar to how for HTTPS we send what Chrome sent)

**Comment by cdzombak** [comment]
> We should probably do something like send whatever the most recent OpenSSH sends and then just call that `p22.ssh.v2`.

So this diff would change to `SUBPROTO_V2 = 39;`?

**Pull request merged**
